export const PICTURE_DETAILS_FETCH_START = "PICTURE_DETAILS_FETCH_START";
export const PICTURE_DETAILS_FETCH_SUCCESS = "PICTURE_DETAILS_FETCH_SUCCESS";
export const PICTURE_DETAILS_FETCH_FAILURE = "PICTURE_DETAILS_FETCH_FAILURE";
